name: mobile
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc:
  equatable:
  intl:
  easy_localization:
  shared_preferences:
  get_it:
  flutter_svg:
  dartz:
  dio:
  shimmer:
  firebase_messaging:
  firebase_core:
  flutter_local_notifications:
  logger:
  go_router:
  google_maps_flutter:
  google_maps_flutter_android:
  google_maps_flutter_platform_interface:
  permission_handler:
  timeago:
  google_sign_in: ^7.2.0
  timer_count_down: ^2.2.2
  geolocator: ^14.0.2
  flutter_dotenv: ^6.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/
    - assets/icons/
    - assets/language/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
