import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.io.FileInputStream
import java.util.Properties

plugins {
    id("com.android.application")
    id("kotlin-android")
    id("dev.flutter.flutter-gradle-plugin")
//    id("com.google.gms.google-services")
}

// ── Load MAPS_API_KEY from gitignored local.properties ──
// local.properties is auto-generated by Flutter and excluded from git.
// Each developer fills in their own MAPS_API_KEY (restricted by Google
// Cloud Console to their package name + debug-keystore SHA-1).
// The value is injected into AndroidManifest.xml via manifestPlaceholders
// in defaultConfig below.
val mapsApiKey: String = run {
    val localProperties = Properties()
    val localPropertiesFile = rootProject.file("local.properties")
    if (localPropertiesFile.exists()) {
        FileInputStream(localPropertiesFile).use { localProperties.load(it) }
    }
    localProperties.getProperty("MAPS_API_KEY", "")
}

android {
    namespace = "com.omar.mobile"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = "27.0.12077973"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
        isCoreLibraryDesugaringEnabled = true
    }

    // Kotlin 2.3 removed the old `kotlinOptions { jvmTarget = "..." }` block;
    // the replacement lives at the top level under `kotlin { compilerOptions { } }`
    // and takes a JvmTarget enum instead of a stringified Java version.
    kotlin {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    defaultConfig {
        applicationId = "com.omar.mobile"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        // Substituted into AndroidManifest.xml's ${MAPS_API_KEY} placeholder
        // (used by com.google.android.geo.API_KEY meta-data).
        manifestPlaceholders["MAPS_API_KEY"] = mapsApiKey
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
}

flutter {
    source = "../.."
}
